theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins
title: HCS of Boolean SAT Formulas
description: Capturing the Structure of Practical SAT Instances
show_downloads: false
markdown: kramdown
